### ISSUE TITLE
How to implement  face Recognition in android   and where is the source code of face Recognisation

### ISSUE THREAD

**Issue by rspapneja** [natiginfo/biometricprompt-compat-java#1]

**Comment by natiginfo** [comment]
Hi, according to documentation:
`On devices running P and above, this will show a system-provided authentication prompt, using a device’s supported biometric (fingerprint, iris, face, etc).`
So, I'm not sure if there's any device which has implemented BiometricPrompt for face recognition. If there is, you can use same code and it should automatically use facial recognition.
