### ISSUE TITLE
Bio-Metric Prompt is not displayed on android P and above devices

### ISSUE THREAD

**Issue by parthdesai1208** [natiginfo/biometricprompt-compat-java#2]
Below is the screenshot of my device (OnePlus 6T) having Android 9.0(Pie).
when I click on "authentication" button, fingerprint prompt is not showing. 
@natiginfo please help me out. 
![Screenshot_20190424-132253](https://user-images.githubusercontent.com/28099478/56803563-98aa3d00-6840-11e9-9e36-db21588bff0c.jpg)

**Comment by benz93chung** [comment]
I have experienced this as well. Are there any solutions?
